Laboratorio 2
Percy Matthew Jacobs Orellana


```{r}
library(nycflights13)
library(tidyverse)
```

Explorando contenido
```{r}
View(flights)
View(airports)
View(planes)
View(airlines)
View(weather)
```

1. Inner-join
```{r}
## 1.1.
flights %>%
  inner_join(planes, by="tailnum", suffix=c('_flights','_planes'))
```

```{r}
## 1.2.
flights %>%
  inner_join(airlines, by="carrier")
```

```{r}
## 1.3.
flights %>%
  inner_join(airports, by=c("origin"="faa"), suffix=c('_flights','_airports_origin')) %>%
  inner_join(airports, by=c("dest"="faa"), suffix=c('_flights','_airports_dest'))
```

```{r}
## 1.4.
flights %>%
  inner_join(weather, by=c("year","month","day","hour","origin"), suffix=c('_flights','_weather'))
```

2. Data manipulation
```{r}
## 2.1.
flights %>%
  count(year, month, day) %>%
  filter(n > 1000) %>%
  arrange(n)
```

```{r}
## 2.2
flights_selected <- flights %>%
  select(year:day, hour, origin, dest, tailnum, carrier, arr_delay, dep_delay)
```

```{r}
## 2.3.
airlines %>%
  left_join(flights_selected, by="carrier") %>%
  select(-origin, -dest) %>%
  mutate(tot_delay = arr_delay + dep_delay)
```

```{r}
## 2.4.
precip_delay <- flights %>%
  inner_join(weather, by=c("year","month","day","hour","origin"), suffix=c('_flights','_weather')) %>%
  group_by(precip) %>%
  summarize(delay = mean(dep_delay, na.rm=TRUE)) %>%
  mutate(delay=replace_na(delay,0))
```

```{r}
## 2.5.
ggplot(precip_delay, aes(x=precip, y=delay)) +
  geom_point()
```

```{r}
## 2.6.
flights_airports <- flights %>%
  filter(year==2013, month==5, day==10) %>%
  group_by(dest) %>%
  summarize(delay = mean(arr_delay, na.rm = TRUE)) %>%
  inner_join(airports, by=c("dest"="faa"))
```

```{r}
## 2.7.
ggplot(flights_airports, aes(x=lon, y=lat, color=delay, size=delay)) +
  geom_point()
```

```{r}
## 2.8.
flights %>%
  inner_join(planes, by="tailnum", suffix=c('_flights','_planes')) %>%
  transmute(tailnum, manufacturer, pi = (dep_delay + arr_delay)/air_time)
```

